#!/usr/bin/env bash
# VANT Signage Agent — Linux Bootstrap Installer
#
# Usage (one-liner):
#   curl -sL https://raw.githubusercontent.com/YOUR_ORG/YOUR_REPO/main/agent/install/setup.sh \
#     | sudo bash -s -- --token vprov_XXXX --server https://customdigitalsignage-api-production.up.railway.app
#
# Or, after downloading the config.yaml from the dashboard:
#   sudo bash setup.sh --config /path/to/config.yaml
#
# Supported distros: Raspberry Pi OS (Bullseye/Bookworm), Ubuntu 22.04+, Debian 11+
# Requires: sudo / root

set -euo pipefail

# ─── Defaults ────────────────────────────────────────────────────────────────

PROVISIONING_TOKEN=""
SERVER_URL=""
CONFIG_FILE=""
INSTALL_USER="${SUDO_USER:-pi}"
CONFIG_DIR="/etc/vant-agent"
CONFIG_PATH="${CONFIG_DIR}/config.yaml"
VANT_AGENT_VERSION="latest"
PYTHON_MIN="3.11"

# ─── Args parsing ─────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --token)   PROVISIONING_TOKEN="$2"; shift 2 ;;
    --server)  SERVER_URL="$2";         shift 2 ;;
    --config)  CONFIG_FILE="$2";        shift 2 ;;
    --user)    INSTALL_USER="$2";       shift 2 ;;
    --version) VANT_AGENT_VERSION="$2"; shift 2 ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--token TOKEN] [--server URL] [--config PATH] [--user USER]"
      exit 1
      ;;
  esac
done

# ─── Root check ───────────────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root (use sudo)." >&2
  exit 1
fi

# ─── Helpers ──────────────────────────────────────────────────────────────────

log()  { echo "[vant-setup] $*"; }
warn() { echo "[vant-setup] WARN: $*" >&2; }
die()  { echo "[vant-setup] ERROR: $*" >&2; exit 1; }

# Detect package manager
if command -v apt-get &>/dev/null; then
  PKG_MGR="apt"
elif command -v dnf &>/dev/null; then
  PKG_MGR="dnf"
else
  die "Unsupported package manager. This installer supports apt and dnf."
fi

install_pkg() {
  if [[ "$PKG_MGR" == "apt" ]]; then
    DEBIAN_FRONTEND=noninteractive apt-get install -y "$@"
  else
    dnf install -y "$@"
  fi
}

# ─── System dependencies ──────────────────────────────────────────────────────

log "Updating package index..."
if [[ "$PKG_MGR" == "apt" ]]; then
  apt-get update -q
else
  dnf check-update -q || true
fi

log "Installing system dependencies..."
APT_PKGS=(python3 python3-pip python3-venv mpv chromium-browser curl ca-certificates)
DNF_PKGS=(python3 python3-pip mpv chromium curl ca-certificates)

if [[ "$PKG_MGR" == "apt" ]]; then
  install_pkg "${APT_PKGS[@]}"
else
  install_pkg "${DNF_PKGS[@]}"
fi

# ─── Python version check ─────────────────────────────────────────────────────

PYTHON_BIN=""
for bin in python3.11 python3.12 python3.13 python3; do
  if command -v "$bin" &>/dev/null; then
    VER=$("$bin" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    MAJOR=${VER%%.*}
    MINOR=${VER##*.}
    if [[ $MAJOR -ge 3 && $MINOR -ge 11 ]]; then
      PYTHON_BIN="$bin"
      break
    fi
  fi
done

if [[ -z "$PYTHON_BIN" ]]; then
  die "Python ${PYTHON_MIN}+ is required but not found. Install it manually and re-run."
fi
log "Using Python: $($PYTHON_BIN --version)"

# ─── Install vant-agent ───────────────────────────────────────────────────────

VENV_DIR="/opt/vant-agent"
log "Creating venv at ${VENV_DIR}..."
"$PYTHON_BIN" -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip --quiet

if [[ "$VANT_AGENT_VERSION" == "latest" ]]; then
  log "Installing vant-agent (latest)..."
  # TODO: replace with real PyPI package name once published
  # "$VENV_DIR/bin/pip" install vant-agent --quiet
  # For now, install from git:
  "$VENV_DIR/bin/pip" install "git+https://github.com/YOUR_ORG/YOUR_REPO.git#subdirectory=agent" --quiet 2>/dev/null \
    || warn "Could not install from git — make sure vant-agent is on PyPI or provide the correct repo URL."
else
  "$VENV_DIR/bin/pip" install "vant-agent==${VANT_AGENT_VERSION}" --quiet
fi

# Symlink binary
ln -sf "${VENV_DIR}/bin/vant-agent" /usr/local/bin/vant-agent
log "vant-agent installed at /usr/local/bin/vant-agent"

# ─── Write config ─────────────────────────────────────────────────────────────

mkdir -p "$CONFIG_DIR"
chmod 750 "$CONFIG_DIR"
chown "root:${INSTALL_USER}" "$CONFIG_DIR" 2>/dev/null || chown "root:root" "$CONFIG_DIR"

if [[ -n "$CONFIG_FILE" ]]; then
  log "Copying config from ${CONFIG_FILE}..."
  cp "$CONFIG_FILE" "$CONFIG_PATH"
elif [[ -n "$PROVISIONING_TOKEN" ]]; then
  log "Writing config with provisioning token..."
  if [[ -z "$SERVER_URL" ]]; then
    die "--server URL is required when using --token. Example: --server https://your-api.up.railway.app"
  fi
  cat > "$CONFIG_PATH" <<EOF
# VANT Signage Agent — auto-generated by setup.sh
server_url: ${SERVER_URL}
provisioning_token: ${PROVISIONING_TOKEN}
cache_dir: /var/cache/vant-agent
log_level: info
manifest_interval: 300
heartbeat_interval: 30
telemetry_interval: 60
EOF
else
  log "No --token or --config provided. Writing example config — edit ${CONFIG_PATH} before starting the agent."
  cat > "$CONFIG_PATH" <<'EOF'
# VANT Signage Agent — edit before starting
server_url: https://REPLACE_WITH_YOUR_API_URL
provisioning_token: vprov_REPLACE_WITH_TOKEN_FROM_DASHBOARD
cache_dir: /var/cache/vant-agent
log_level: info
manifest_interval: 300
heartbeat_interval: 30
telemetry_interval: 60
EOF
fi

chmod 640 "$CONFIG_PATH"
chown "root:${INSTALL_USER}" "$CONFIG_PATH" 2>/dev/null || chown "root:root" "$CONFIG_PATH"

# ─── Cache directory ──────────────────────────────────────────────────────────

CACHE_DIR="/var/cache/vant-agent"
mkdir -p "$CACHE_DIR"
if id "$INSTALL_USER" &>/dev/null; then
  chown -R "${INSTALL_USER}:${INSTALL_USER}" "$CACHE_DIR"
fi

# ─── Systemd service ──────────────────────────────────────────────────────────

SERVICE_FILE="/etc/systemd/system/vant-agent.service"
log "Installing systemd service..."
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=VANT Signage Display Agent
After=network-online.target graphical-session.target
Wants=network-online.target

[Service]
Type=simple
User=${INSTALL_USER}
Group=${INSTALL_USER}
WorkingDirectory=/home/${INSTALL_USER}
Environment=VANT_CONFIG=${CONFIG_PATH}
Environment=DISPLAY=:0
ExecStart=/usr/local/bin/vant-agent run
Restart=on-failure
RestartSec=10
StartLimitInterval=60
StartLimitBurst=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=vant-agent

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable vant-agent

# ─── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VANT Signage Agent installed successfully"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Config:   ${CONFIG_PATH}"
echo "  Binary:   /usr/local/bin/vant-agent"
echo "  Service:  systemctl status vant-agent"
echo ""

if grep -q "REPLACE_WITH" "$CONFIG_PATH" 2>/dev/null; then
  echo "  ⚠  Edit ${CONFIG_PATH} with your server URL and provisioning token."
  echo "     Then run: sudo systemctl start vant-agent"
else
  echo "  Starting agent..."
  systemctl start vant-agent
  echo "  Run 'journalctl -fu vant-agent' to follow logs."
fi
echo ""
